version: '3'

services:
  db:
    build: ./build/oracle
    ports:
    - '1521:1521'
    environment:
    - TZ=Asia/Shanghai
    volumes:
    - ./install:/install
    - ./scripts:/scripts
    - ./oracle/app:/opt/oracle/app
    - ./oracle/dpdump:/opt/oracle/dpdump 
    privileged: true
    restart: always

  # 健康检查服务
  autoheal:
    image: willfarrell/autoheal
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment: 
    - AUTOHEAL_CONTAINER_LABEL=all